import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Styles from './../styles/Home.module.css'
import Script from 'next/script'
import Image from 'next/image'
import Link from 'next/link'
import Carousel from '@/components/Carousel'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ncc Udaan-Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/UdaanLogo.png" />
        {/* <link rel="icon" href="/Rectangle.svg" />  */}
      </Head>
      <Script src='https://kit.fontawesome.com/16ae4a1ead.js' crossOrigin='anonymous' strategy='lazyOnload' />
      <Navbar />
      <main className={Styles.main}>
        <div className={Styles.banner}>
          <div className='Logo'>
            <Image src="/UdaanLogo.png" width={185} height={95} alt='Udaan Logo' />
          </div>
          <h1>Agency<span>Name</span></h1>
          <h2>NCC UDAAN initiative</h2>
          <hr />
          <p>This is a dummy statement regarding the branding of the E-Commerce site or the products to be sold at that site.</p>
          <div>
            <span><Link href="#">www.website.com</Link></span>
            <div className="social">
              <span><Link href="#"><i className="fa-brands fa-facebook"></i></Link></span>
              <span><Link href="#"><i className="fa-brands fa-instagram"></i></Link></span>
              <span><Link href="#"><i className="fa-brands fa-linkedin"></i></Link></span>
            </div>
          </div>
        </div>
        <Carousel />
      </main>
      <Footer />
    </>

  )
}
