import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Image from 'next/image'
import Link from 'next/link'
import Carousel from '@/components/Carousel'
import bullseye from '#/🦆 illustration _target aim_.png'
import TeamworkLogo from '#/🦆 illustration _Team Work_.png'
import LeftVisionImage from '#/Ellipse 21.png'
import RighVisionImage from '#/Ellipse 22.png'
import Rule from '@/components/Rule'
import {Users} from "@phosphor-icons/react"
import {FacebookLogo,InstagramLogo,LinkedinLogo} from '@phosphor-icons/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ncc Udaan-Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/UdaanLogo.png" />
        {/* <link rel="icon" href="/Rectangle.svg" />  */}
      </Head>
      <Script src='https://kit.fontawesome.com/16ae4a1ead.js' crossOrigin='anonymous' strategy='lazyOnload' />
      <Navbar />
      <main className={Styles.main}>


        <Carousel />

        <div className={Styles.banner}>
          <div className={Styles.Logo}>
            <Image src="/UdaanLogo.png" width={185} height={95} alt='Udaan Logo' />
          </div>
          <h1>Agency <span className={Styles.headingblue}>Name</span></h1>
          <h2>NCC UDAAN initiative</h2>
          <hr />
          <p>This is a dummy statement regarding the branding of the E-Commerce site or the products to be sold at that site. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate explicabo quasi itaque aperiam consequuntur cumque quibusdam reprehenderit impedit rem soluta!</p>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. At pariatur delectus, quo tempora suscipit fuga mollitia eius facere non et quisquam quae dolore repellat cupiditate ullam iusto, enim nihil a consequuntur facilis soluta. Autem voluptate non qui explicabo molestias unde?</p>
          <div className={Styles.contact}>
            <span><Link href="#">www.website.com</Link></span>
            <div className={Styles.social}>
              <span><Link href="#"><FacebookLogo size={24} /></Link></span>
              <span><Link href="#"><InstagramLogo size={24}/></Link></span>
              <span><Link href="#"><LinkedinLogo size={24}></LinkedinLogo></Link></span>
            </div>
          </div>
        </div>



        <div className={Styles.aimSection}>
          <div className={Styles.aimContainer}>
            <div className={Styles.aimimage}>
              <Image alt='Bulls eye board' src={bullseye} ></Image>
              <div className={Styles.Aimquestion}>
                <h1>Aims of NCC UDAAN ?</h1>
                <Rule />
              </div>
            </div>
            <div className={Styles.aimtext}>
              <h3>Write few lines on the aim and objectives of UDAAN</h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae mollitia assumenda natus temporibus et facere ratione possimus incidunt voluptatem quod laudantium quaerat eligendi deserunt veniam id architecto fugit quo cumque tempora, ut aperiam repudiandae! Aut necessitatibus eligendi sapiente quis nulla quae, perspiciatis voluptas quos obcaecati ipsa. Iste quod asperiores facilis.</p>
            </div>
          </div>
        </div>




        <div className={Styles.FirstResponder}>
          <div className={Styles.FirstResponderContainer}>
            <div className={Styles.leftsideImage}>
              <Image alt='Ncc training image' src={LeftVisionImage}></Image>
            </div>
            <div className={Styles.VisionMission}>
              <Image alt='Team work Image' src={TeamworkLogo} ></Image>
              <div className={Styles.Visioncontainer}>
                <h1>Vision and Mission</h1>
                <Rule />
              </div>
              <div className={Styles.Visiontext}>
                <h3>Write few lines on the vision and mission of UDAAN</h3>
              </div>
              <button> <span><Users size={24} /></span>First Responder</button>
            </div>
            <div className={Styles.rightsideImage}>
            <Image alt='Ncc training image' src={RighVisionImage}></Image>
            </div>
          </div>
        </div>
      </main>



      <Footer />


    </>

  )
}
